// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCHDvu7kkrOkPDJkHaC5rqO9Uxb3IMrMsM',
    appId: '1:30911898471:web:d7b721090aac6b180d45c2',
    messagingSenderId: '30911898471',
    databaseURL: 'https://plant-monitoring-capstone-default-rtdb.asia-southeast1.firebasedatabase.app/',
    projectId: 'plant-monitoring-capstone',
    authDomain: 'plant-monitoring-capstone.firebaseapp.com',
    storageBucket: 'plant-monitoring-capstone.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC1ikLg4QR-Z52_p238ncTtZJt_flhWQXY',
    appId: '1:30911898471:android:19235fdf5198971b0d45c2',
    messagingSenderId: '30911898471',
    projectId: 'plant-monitoring-capstone',
    storageBucket: 'plant-monitoring-capstone.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAgByj26wX_9D9NIjnsg8OmjM8DW6qza5o',
    appId: '1:30911898471:ios:6fcd5885417b02430d45c2',
    messagingSenderId: '30911898471',
    projectId: 'plant-monitoring-capstone',
    storageBucket: 'plant-monitoring-capstone.firebasestorage.app',
    iosBundleId: 'com.example.flutterApplication1',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAgByj26wX_9D9NIjnsg8OmjM8DW6qza5o',
    appId: '1:30911898471:ios:6fcd5885417b02430d45c2',
    messagingSenderId: '30911898471',
    projectId: 'plant-monitoring-capstone',
    storageBucket: 'plant-monitoring-capstone.firebasestorage.app',
    iosBundleId: 'com.example.flutterApplication1',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCHDvu7kkrOkPDJkHaC5rqO9Uxb3IMrMsM',
    appId: '1:30911898471:web:0665d285ed41f2210d45c2',
    messagingSenderId: '30911898471',
    projectId: 'plant-monitoring-capstone',
    authDomain: 'plant-monitoring-capstone.firebaseapp.com',
    storageBucket: 'plant-monitoring-capstone.firebasestorage.app',
  );
}
